version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "9000:80"
    networks:
      - loadbalancing
    depends_on:
      - bank-1
      - bank-2
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  bank-1:
    image: actor4k-bank
    restart: unless-stopped
    environment:
      ACTOR4K_NODE_ID: bank-1
      ACTOR4K_INITIAL_GROUP_MEMBERS: bank-1::bank-1:61100,bank-2::bank-2:61100
    ports:
      - "9001:9000"
    networks:
      loadbalancing:
  bank-2:
    image: actor4k-bank
    restart: unless-stopped
    environment:
      ACTOR4K_NODE_ID: bank-2
      ACTOR4K_INITIAL_GROUP_MEMBERS: bank-1::bank-1:61100,bank-2::bank-2:61100
    ports:
      - "9002:9000"
    networks:
      loadbalancing:
networks:
  loadbalancing: