services:
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "9000:80"
    networks:
      - loadbalancing
    depends_on:
      - bank-1
      - bank-2
      - bank-3
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  bank-1:
    image: microbank
    restart: unless-stopped
    environment:
      ACTOR4K_NODE_ID: bank-1
      ACTOR4K_SEED_MEMBERS: bank-1::bank-1:61000,bank-2::bank-2:61000,bank-3::bank-3:61000
    ports:
      - "9001:9000"
    networks:
      loadbalancing:
  bank-2:
    image: microbank
    restart: unless-stopped
    environment:
      ACTOR4K_NODE_ID: bank-2
      ACTOR4K_SEED_MEMBERS: bank-1::bank-1:61000,bank-2::bank-2:61000,bank-3::bank-3:61000
    ports:
      - "9002:9000"
    networks:
      loadbalancing:
  bank-3:
    image: microbank
    restart: unless-stopped
    environment:
      ACTOR4K_NODE_ID: bank-3
      ACTOR4K_SEED_MEMBERS: bank-1::bank-1:61000,bank-2::bank-2:61000,bank-3::bank-3:61000
    ports:
      - "9003:9000"
    networks:
      loadbalancing:
  bank-4:
    image: microbank
    restart: unless-stopped
    environment:
      ACTOR4K_NODE_ID: bank-4
      ACTOR4K_SEED_MEMBERS: bank-1::bank-1:61000,bank-2::bank-2:61000,bank-3::bank-3:61000,bank-4::bank-4:61000
    ports:
      - "9004:9000"
    networks:
      loadbalancing:
    profiles:
      - donotstart
networks:
  loadbalancing: