[versions]
# https://plugins.gradle.org/plugin/org.jetbrains.kotlin.jvm
kotlin = "2.1.10"
# https://github.com/Kotlin/kotlinx.coroutines
kotlinx-coroutines = "1.10.1"
# https://github.com/vanniktech/gradle-maven-publish-plugin
publish = "0.30.0"
# https://github.com/Kotlin/dokka
dokka = "2.0.0"
# https://mvnrepository.com/artifact/org.slf4j/slf4j-api
slf4j = "2.0.16"
# https://github.com/Kotlin/kotlinx-datetime
kotlinx-datetime = "0.6.2"

[libraries]
gradle-kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-publish-plugin = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "publish" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-reload4j = { module = "org.slf4j:slf4j-reload4j", version.ref = "slf4j" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
pubhish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
