services:
  haproxy:
    image: haproxytech/haproxy-alpine
    restart: unless-stopped
    ports:
      - "9000:80"
      - "8404:8404"
    networks:
      - loadbalancing
    depends_on:
      - bank-1
      - bank-2
      - bank-3
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

  bank-1:
    image: microbank-jvm
    restart: unless-stopped
    environment:
      ACTOR4K_CURRENT_NODE: bank-1
      ACTOR4K_NODES: bank-1::bank-1:6000,bank-2::bank-2:6000,bank-3::bank-3:6000
    ports:
      - "9001:6000"
    networks:
      loadbalancing:
  bank-2:
    image: microbank-jvm
    restart: unless-stopped
    environment:
      ACTOR4K_CURRENT_NODE: bank-2
      ACTOR4K_NODES: bank-1::bank-1:6000,bank-2::bank-2:6000,bank-3::bank-3:6000
    ports:
      - "9002:6000"
    networks:
      loadbalancing:
  bank-3:
    image: microbank-jvm
    restart: unless-stopped
    environment:
      ACTOR4K_CURRENT_NODE: bank-3
      ACTOR4K_NODES: bank-1::bank-1:6000,bank-2::bank-2:6000,bank-3::bank-3:6000
    ports:
      - "9003:6000"
    networks:
      loadbalancing:
  bank-4:
    image: microbank-jvm
    restart: unless-stopped
    environment:
      ACTOR4K_CURRENT_NODE: bank-4
      ACTOR4K_CURRENT_NODE_IS_PROXY: true
      ACTOR4K_NODES: bank-1::bank-1:6000,bank-2::bank-2:6000,bank-3::bank-3:6000,bank-4::bank-4:6000
    ports:
      - "9004:6000"
    networks:
      loadbalancing:
networks:
  loadbalancing: